version: '3'

volumes:
  redis_data:
  redis_conf:

services:

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/root/redis
      - redis_conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  backend:
    build: ./
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    command:
      ["uvicorn", "src.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000" ]
    ports:
      - 127.0.0.1:8000:8000