version: '3'

volumes:
  redis_data:
  redis_conf:

services:

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/root/redis
      - redis_conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 127.0.0.1:6379:6379